# Generated by Django 5.1.1 on 2025-04-01 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_auto_20250401_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='created_at',
        ),
    ]
