# Generated by Django 5.1.1 on 2025-04-01 19:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40)),
                ('date_of_birth', models.DateTimeField()),
                ('idnumber', models.CharField(max_length=40)),
                ('phone_number', models.IntegerField()),
                ('email_adress', models.EmailField(default='default@gmail.com', max_length=254, unique=True)),
                ('fiscal_idnum', models.CharField(max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40)),
                ('date_of_birth', models.DateTimeField()),
                ('idnumber', models.CharField(max_length=40)),
                ('phone_number', models.IntegerField()),
                ('email_adress', models.EmailField(default='default@gmail.com', max_length=254, unique=True)),
                ('fiscal_idnum', models.CharField(max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(13)])),
                ('guardian', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.guardian')),
                ('inscriptions', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='inscriptions.inscription')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
