# Generated by Django 5.1.1 on 2025-04-04 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20250401_2201'),
    ]

    operations = [
        migrations.AlterField (
            model_name='student',
            name = 'inscriptions',
            field =models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_inscription', null=True, to='inscriptions.inscription'),
        ),
    ]
