# Generated by Django 5.1.1 on 2025-04-01 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40)),
                ('date_of_birth', models.DateTimeField()),
                ('idnumber', models.CharField(max_length=40)),
                ('phone_number', models.IntegerField()),
                ('email_adress', models.EmailField(default='default@gmail.com', max_length=254, unique=True)),
                ('fiscal_idnum', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'pendente'), ('approved', 'aprovado'), ('rejected', 'rejeitado')], default='pending', max_length=20)),
                ('grade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(13)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
